"""Stable contracts for the refactored Texto Off pipeline — Milestone 1A."""

from __future__ import annotations

SCHEMA_VERSION = 1
PIPELINE_ALGORITHM = "textoff_pipeline_milestone_1a"

ELIGIBILITY_REMOVE = "REMOVER"
ELIGIBILITY_PROTECT = "PROTEGER"
ELIGIBILITY_UNCERTAIN = "INCERTO"

VISUAL_NEUTRAL_UNIFORM = "NEUTRO_UNIFORME"
VISUAL_COLOR_UNIFORM = "COR_UNIFORME"
VISUAL_GRADIENT = "GRADIENTE"
VISUAL_TEXTURE = "TEXTURA"
VISUAL_TRANSPARENT = "TRANSPARENTE"
VISUAL_UNCERTAIN = "INCERTO"

ROUTE_PROTECT = "PROTEGER"
ROUTE_REVIEW = "REVIEW"
ROUTE_LEVEL_3 = "LEVEL_3"
ROUTE_LEVEL_4 = "LEVEL_4"
ROUTE_LEVEL_5 = "LEVEL_5"

MILESTONE_1A_REASON = "MILESTONE_1A_FAIL_CLOSED"

VALID_ELIGIBILITY = {
    ELIGIBILITY_REMOVE,
    ELIGIBILITY_PROTECT,
    ELIGIBILITY_UNCERTAIN,
}
VALID_VISUAL_PROFILES = {
    VISUAL_NEUTRAL_UNIFORM,
    VISUAL_COLOR_UNIFORM,
    VISUAL_GRADIENT,
    VISUAL_TEXTURE,
    VISUAL_TRANSPARENT,
    VISUAL_UNCERTAIN,
}
VALID_ROUTES = {
    ROUTE_PROTECT,
    ROUTE_REVIEW,
    ROUTE_LEVEL_3,
    ROUTE_LEVEL_4,
    ROUTE_LEVEL_5,
}
